export default {
  es: [
    "Opciones",
    "Primer temporizador",
    "Minutos",
    "Segundos",
    "Segundo temporizador",
    "Minutos",
    "Segundos",
    "Modo ganador",
    "Puntos",
    "Modo total",
    "Puntos",
    "Texto personalizado",
    "Descargar resultados",
    "Guardar",
    "Reiniciar",
    "Versión 1.0",
    "15/06/2022",
  ],
  fr: [
    "Options",
    "Première minuterie",
    "Minutes",
    "Secondes",
    "Deuxième minuterie",
    "Minutes",
    "Secondes",
    "Mode gagnant",
    "Points",
    "Mode total",
    "Points",
    "Objectif atteint!",
    "Texte personnalisé",
    "Téléchargez les résultats",
    "Version 1.0",
    "15/06/2022",
    "Sauvegarder",
    "Redémarrer",
  ],
  de: [
    "Optionen",
    "Erster Timer",
    "Minuten",
    "Sekunden",
    "Zweiter Timer",
    "Minuten",
    "Sekunden",
    "Gewinnmodus",
    "Punkte",
    "Vollmodus",
    "Punkte",
    "Ziel erreicht!",
    "Benutzerdefinierter Text",
    "Ergebnisse herunterladen",
    "Version 1.0",
    "2022/06/15",
    "Speichern",
    "Neu starten",
  ],
};
