// https://github.com/j-alarcon
export default {
  es: [
    "Opciones",
    "1er temporizador",
    "Minutos",
    "Segundos",
    "2ndo temporizador",
    "Minutos",
    "Segundos",
    "Modo ganador",
    "Puntos",
    "Modo total",
    "Puntos",
    "Texto personalizado",
    "Descargar resultados",
    "Guardar",
    "Reiniciar",
    "Versión 1.1",
    "23/08/2022",
    "EQUIPO 1",
  ],
  fr: [
    "Options",
    "1ème minuterie",
    "Minutes",
    "Secondes",
    "2ème minuterie",
    "Minutes",
    "Secondes",
    "Mode gagnant",
    "Points",
    "Mode total",
    "Points",
    "Texte personnalisé",
    "Téléchargez les résultats",
    "Sauvegarder",
    "Redémarrer",
    "Version 1.1",
    "23/08/2022",
    "ÉQUIPE 1" 
  ],
  de: [
    "Optionen",
    "Erster Timer",
    "Minuten",
    "Sekunden",
    "Zweiter Timer",
    "Minuten",
    "Sekunden",
    "Gewinnmodus",
    "Punkte",
    "Vollmodus",
    "Punkte",
    "Benutzerdefinierter Text",
    "Ergebnisse herunterladen",
    "Speichern",
    "Neu starten",
    "Version 1.1",
    "2022/08/23",
    "MANNSCHAFT 1"
  ],
};
